module.exports = {
  onBoardImg: require('../../assets/images/onBoardImg.png'),
  onBoardImg1: require('../../assets/images/onBoardImg1.png'),
  onBoardImg2: require('../../assets/images/onBoardImg2.png'),
  onBoardImg3: require('../../assets/images/onBoardImg3.png'),
  locationlocationIllustration: require('../../assets/images/location-illustration.png'),
  dryWash: require('../../assets/images/washing.png'),
  wash: require('../../assets/images/wash.png'),
  ironing: require('../../assets/images/ironing.png'),
  tShirtWashIron: require('../../assets/images/t-ShirtWashIron.png'),
  washingWash: require('../../assets/images/washingWash.png'),
  ironinWash: require('../.../../../assets/images/ironinWash.png'),
  offer:require('../../assets/images/offer.png'),
  offer1:require('../../assets/images/offer1.png'),
  offer2:require('../../assets/images/offer2.png'),
  deliveryman: require('../../assets/images/deliveryman.png'),
  delivery: require('../../assets/images/delivery.png'),
  socksClean: require('../../assets/images/socksClean.png'),
  service: require('../../assets/images/service.png'),
  service1: require('../../assets/images/service1.png'),
  service2: require('../../assets/images/service2.png'),
  service3: require('../../assets/images/service3.png'),
  service4: require('../../assets/images/service4.png'),
  service5: require('../../assets/images/service5.png'),
  service6: require('../../assets/images/service6.png'),
  service7: require('../../assets/images/service7.png'),
  service8: require('../../assets/images/service8.png'),
  service9: require('../../assets/images/service9.png'),
  service10: require('../../assets/images/service10.png'),
    service11: require('../../assets/images/service11.png'),
      service12: require('../../assets/images/service12.png'),
        service13: require('../../assets/images/service13.png'),
          service14: require('../../assets/images/service14.png'),
            service15: require('../../assets/images/service15.png'),
              service16: require('../../assets/images/service16.png'),
                service17: require('../../assets/images/service17.png'),
                  service18: require('../../assets/images/service18.png'),
                    service19: require('../../assets/images/service19.png'),
      
        
  
  
}